# port: 9494
# socks-port: 9595
# mixed-port: 9696
redir-port: 9797
tproxy-port: 9898
mode: rule
allow-lan: true
unified-delay: false
bind-address: '*'
# info / warning / error / debug / silent
log-level: warning
ipv6: true
geodata-mode: false
geodata-loader: memconservative
external-controller: 0.0.0.0:9090 
external-controller-tls: 0.0.0.0:9091 # RESTful API HTTPS
# secret: "123456"
external-ui: ./dashboard/dist
proxies:
proxy-providers:
  proxy:
    type: http
    behavior: proxy
    path: "./proxy_provider/config.yaml"
    url: https://config.v2cross.com/clashprofile/config/
    health-check:
      enable: true
      url: http://www.google.com/
    interval: 500
  China:
    type: http
    url: "https://free.iam7.tk/clash/proxies?c=CN&speed=5"
    path: free.iam7.tk/provider-China.yaml
    interval: 60
    health-check:
      enable: true
      interval: 300
      url: http://www.google.com/
  HongKong:
    type: http
    url: "https://free.iam7.tk/clash/proxies?c=HK&speed=5"
    path: free.iam7.tk/provider-HongKong.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/
  Taiwan:
    type: http
    url: "https://free.iam7.tk/clash/proxies?c=TW&speed=5"
    path: free.iam7.tk/provider-Taiwan.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/ 
  Speed:
    type: http
    url: "https://free.iam7.tk/clash/proxies?speed=10"
    path: free.iam7.tk/provider-Speed.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/      
  Relay:
    type: http
    url: "https://free.iam7.tk/clash/proxies?filter=r&speed=5"
    path: free.iam7.tk/provider-Relay.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/
  Pool:
    type: http
    url: "https://free.iam7.tk/clash/proxies?filter=p&speed=5"
    path: free.iam7.tk/provider-Pool.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/ 
  ss:
    type: http
    url: "https://free.iam7.tk/clash/proxies?type=ss&speed=5"
    path: free.iam7.tk/provider-ss.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/
  ssr:
    type: http
    url: "https://free.iam7.tk/clash/proxies?type=ssr&speed=5"
    path: free.iam7.tk/provider-ssr.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/
  v2ray:
    type: http
    url: "https://free.iam7.tk/clash/proxies?type=vmess&speed=5"
    path: free.iam7.tk/provider-vmess.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/ 
  trojan:
    type: http
    url: "https://free.iam7.tk/clash/proxies?type=trojan&speed=5"
    path: free.iam7.tk/provider-trojan.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/      
  Asia:
    type: http
    url: "https://free.iam7.tk/clash/proxies?c=AF,AM,AZ,PS,BH,BD,BT,BN,KH,CY,TL,EG,IN,ID,IR,IQ,IL,JP,JO,KZ,KW,KG,LA,LB,MY,MV,MN,MM,NP,KP,OM,PK,CN,PH,QA,TW,RU,SA,SG,KR,LK,SY,TJ,TH,TR,TM,GE,AE,UZ,VN,YE&speed=5"
    path: free.iam7.tk/provider-Asia.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/ 
  North America:
    type: http
    url: "https://free.iam7.tk/clash/proxies?c=AG,BS,BB,BZ,CA,CR,CU,DM,DO,SV,GD,GT,HT,HN,JM,MX,NI,PA,KN,LC,VC,TT,US&speed=5"
    path: free.iam7.tk/Provider-North America.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/      
  South America:
    type: http
    url: "https://free.iam7.tk/clash/proxies?c=AR,BO,BR,CL,CO,EC,GY,PY,PE,SR,TT,UY,VE&speed=5"
    path: free.iam7.tk/provider-South America.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/
  Oceania:
    type: http
    url: "https://free.iam7.tk/clash/proxies?c=AU,TL,FJ,CK,ID,KI,MH,FM,NR,NZ,PW,PG,WS,SB,NU,TO,TV,VU&speed=5"
    path: free.iam7.tk/provider-Oceania.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/
  Europe:
    type: http
    url: "https://free.iam7.tk/clash/proxies?c=AL,AD,AT,BY,BE,BA,BG,HR,CZ,DK,EE,FI,FR,DE,DR,HU,IS,IE,IT,XK,LV,LI,LT,LU,MT,MK,MD,MC,ME,NL,NO,PL,PT,RO,TU,SM,RS,SK,SI,ES,SE,CH,TR,UA,GB,VA&speed=5"
    path: free.iam7.tk/provider-Europe.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/
  Africa:
    type: http
    url: "https://free.iam7.tk/clash/proxies?c=DZ,AO,BJ,BW,BF,CM,CV,CF,TD,KM,CI,CD,DJ,EG,GQ,ER,ET,GA,GM,GH,GN,GW,KE,LS,LR,LY,MG,MW,ML,MR,MU,MA,MZ,NA,NE,NG,CG,RW,ST,SN,SC,SL,SO,SS,ZA,SD,SZ,TZ,TG,TN,UG,EH,ZM,ZW&speed=5"
    path: free.iam7.tk/Provider-Africa.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/
  others:
    type: http
    url: "https://free.iam7.tk/clash/proxies?nc=CN,HK,TW,JP,KR,RU,SG,IN,VN,TH,MY,PH,ID,NZ,US,CA,MX,AU,NL,DE,GB,FR,DK,ES,FZ,EE,HR,LT,LU,AL,CH,BE,FI&speed=5"
    path: free.iam7.tk/provider-others.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/
  Global:
    type: http
    url: "https://free.iam7.tk/clash/proxies"
    path: free.iam7.tk/provider.yaml
    interval: 60
    health-check:
      enable: true
      interval: 120
      url: http://www.google.com/
proxy-groups:
- name: 🎯 select
  type: select
  proxies:
   - proxys
  use:
   - proxy
   - Global
   - ss
   - ssr
   - others
   - Europe
   - Oceania
   - South America
   - North America
   - Taiwan
   - HongKong
   - China
   - Pool
   - Relay
   - Africa
   - Asia
   - Speed
   - trojan
   - v2ray     
- name: proxys
  type: url-test
  health-check:
  enable: true
  disable-udp: false
  use:
   - proxy
   - Global
   - ss
   - ssr
   - others
   - Europe
   - Oceania
   - South America
   - North America
   - Taiwan
   - HongKong
   - China
   - Pool
   - Relay
   - Africa
   - Asia
   - Speed
   - trojan
   - v2ray
  url: http://www.google.com/
rules:
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve,udp
  - IP-CIDR6,::1/128,REJECT,no-resolve,udp
  # network(tcp/udp) condition for all rules 
  - DOMAIN-SUFFIX,ad.com,REJECT,udp
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT,tcp
  - DOMAIN-SUFFIX,bilibili.com,DIRECT,tcp
  - DOMAIN-SUFFIX,bilibili.com,REJECT,udp
  - DOMAIN-SUFFIX,github.com,DIRECT,no-resolve,tcp
  - DOMAIN-SUFFIX,github.io,DIRECT,no-resolve,tcp
  - DOMAIN-SUFFIX,githubapp.com,DIRECT,no-resolve,tcp
  - DOMAIN-SUFFIX,githubassets.com,DIRECT,no-resolve,tcp
  - DOMAIN-SUFFIX,githubusercontent.com,DIRECT,no-resolve,tcp
  - DOMAIN-KEYWORD,github,DIRECT,no-resolve,tcp
  - DOMAIN-KEYWORD,appteka.store,DIRECT,no-resolve,tcp
  - DOMAIN-SUFFIX,collector.githubapp.com,DIRECT,no-resolve,tcp
  - MATCH,proxys
